name: Web CI

on: [push, pull_request]

env:
  IMAGE_NAME: cicd-demo/web
  NODE_ENV: test

defaults:
  run:
    working-directory: web

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{github.event_name}}"
      - run: echo "${{github.ref}}"

  build:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: web/build

  deploy-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_ENV: pr-{{PR_NUMBER}}
      DEPLOYMENT_DOMAIN: pr-{{PR_NUMBER}}.${{ secrets.WEB_DOMAIN }}
    steps:
      - uses: actions/checkout@v2

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ github.token }}
          target_url: https://${{ env.DEPLOYMENT_DOMAIN }}
          environment: ${{ env.DEPLOYMENT_ENV }}
          ref: ${{ github.sha }}

      - uses: amondnet/vercel-action@v19
        with:
          working-directory: web
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.PR_COMMENTS_GITHUB_TOKEN }}
          scope: ${{ secrets.WEB_ORG_ID }}
          vercel-org-id: ${{ secrets.WEB_ORG_ID }}
          vercel-project-id: ${{ secrets.WEB_PROJECT_ID }}
          alias-domains: |
            ${{ env.DEPLOYMENT_DOMAIN }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://${{ env.DEPLOYMENT_DOMAIN }}
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://${{ env.DEPLOYMENT_DOMAIN }}
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_ENV: production
      DEPLOYMENT_DOMAIN: ${{ secrets.WEB_DOMAIN }}
    steps:
      - uses: actions/checkout@v2

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ github.token }}
          target_url: https://${{ env.DEPLOYMENT_DOMAIN }}
          environment: ${{ env.DEPLOYMENT_ENV }}
          ref: ${{ github.sha }}

      - uses: amondnet/vercel-action@v19
        with:
          working-directory: web
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.PR_COMMENTS_GITHUB_TOKEN }}
          scope: ${{ secrets.WEB_ORG_ID }}
          vercel-org-id: ${{ secrets.WEB_ORG_ID }}
          vercel-project-id: ${{ secrets.WEB_PROJECT_ID }}
          vercel-args: "--prod"

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://${{ env.DEPLOYMENT_DOMAIN }}
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://${{ env.DEPLOYMENT_DOMAIN }}
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
