name: Web CI

on:
  pull_request:
  push:
    branches:
      - "main"

env:
  NODE_ENV: test

defaults:
  run:
    working-directory: web

jobs:
  build:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      - uses: actions/github-script@v3
        id: infra-check-name
        with:
          script: |
            return github.event_name == 'pull_request' ? 'pr_output' : 'apply_output'
          result-encoding: string

      - name: Wait for infra deploy to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ steps.infra-check-name.outputs.result }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 60
      - name: Download infra output
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: infra.yml
          commit: ${{ github.event.pull_request.head.sha || github.sha }}
          name: terraform-output
          path: infra

      - run: cat ../infra/terraform-output.json

      - name: Extract build args from terraform output
        run: |
          if [ -f "../infra/terraform-output.json" ]; then
            TEST_VALUE=$(cat ../infra/terraform-output.json | jq -r '.test.value')
            echo "TEST_VALUE=$TEST_VALUE" >> $GITHUB_ENV
          fi

      - name: Extract prod build args from terraform output
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          if [ -f "../infra/terraform-output.json" ]; then
            SENTRY_DSN=$(cat ../infra/terraform-output.json | jq -r '.sentry_web_project_key_dsn_public.value')
            echo "REACT_APP_SENTRY_DSN=$SENTRY_DSN" >> $GITHUB_ENV
          fi

      - run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: web/build

  deploy-pr:
    if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_ENV: pr-${{ github.event.number }}
      DEPLOYMENT_DOMAIN: pr-${{ github.event.number }}.${{ secrets.WEB_DOMAIN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: web-build
          path: web/build

      - name: start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: ${{ env.DEPLOYMENT_ENV }}

      - uses: amondnet/vercel-action@v19
        with:
          working-directory: web
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.PR_COMMENTS_GITHUB_TOKEN }}
          scope: ${{ secrets.WEB_ORG_ID }}
          vercel-org-id: ${{ secrets.WEB_ORG_ID }}
          vercel-project-id: ${{ secrets.WEB_PROJECT_ID }}
          alias-domains: |
            ${{ env.DEPLOYMENT_DOMAIN }}

      - name: update deployment status
        uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ env.DEPLOYMENT_DOMAIN }}

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_ENV: production
      DEPLOYMENT_DOMAIN: ${{ secrets.WEB_DOMAIN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: web-build
          path: web/build

      - name: start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: ${{ env.DEPLOYMENT_ENV }}

      - uses: amondnet/vercel-action@v19
        with:
          working-directory: web
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.PR_COMMENTS_GITHUB_TOKEN }}
          scope: ${{ secrets.WEB_ORG_ID }}
          vercel-org-id: ${{ secrets.WEB_ORG_ID }}
          vercel-project-id: ${{ secrets.WEB_PROJECT_ID }}
          vercel-args: "--prod"

      - name: update deployment status
        uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ env.DEPLOYMENT_DOMAIN }}
