name: Web CI

on: [push, pull_request]

env:
  IMAGE_NAME: cicd-demo/web
  NODE_ENV: test

defaults:
  run:
    working-directory: web

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{github.event_name}}"
      - run: echo "${{github.ref}}"

  build:
    if: github.event_name == 'pull_request' || github.ref == 'ref/heads/main'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: web/build

  deploy-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          working-directory: web
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.PR_COMMENTS_GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.WEB_ORG_ID }}
          vercel-project-id: ${{ secrets.WEB_PROJECT_ID }}
          alias-domains: |
            pr-{{PR_NUMBER}}.${{ secrets.WEB_DOMAIN }}

  deploy:
    if: github.event_name == 'push' && github.ref == 'ref/heads/main'
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          working-directory: web
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.PR_COMMENTS_GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.WEB_ORG_ID }}
          vercel-project-id: ${{ secrets.WEB_PROJECT_ID }}
          vercel-args: "--prod"
