name: Web CI

on:
  pull_request:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: cicd-demo/web
  NODE_ENV: test

defaults:
  run:
    working-directory: web

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{github.event_name}}"
      - run: echo "${{github.ref}}"
      - run: echo "${{github.event.number}}"
      - run: echo "${{github.event.issue.number}}"

  build:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: web/build

  deploy-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_ENV: pr-${{ github.event.number }}
      DEPLOYMENT_DOMAIN: pr-${{ github.event.number }}.${{ secrets.WEB_DOMAIN }}
    steps:
      - uses: actions/checkout@v2

      - name: start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: ${{ env.DEPLOYMENT_ENV }}

      - uses: amondnet/vercel-action@v19
        with:
          working-directory: web
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.PR_COMMENTS_GITHUB_TOKEN }}
          scope: ${{ secrets.WEB_ORG_ID }}
          vercel-org-id: ${{ secrets.WEB_ORG_ID }}
          vercel-project-id: ${{ secrets.WEB_PROJECT_ID }}
          alias-domains: |
            ${{ env.DEPLOYMENT_DOMAIN }}

      - name: update deployment status
        uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ env.DEPLOYMENT_DOMAIN }}

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_ENV: production
      DEPLOYMENT_DOMAIN: ${{ secrets.WEB_DOMAIN }}
    steps:
      - uses: actions/checkout@v2

      - name: start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          environment: ${{ env.DEPLOYMENT_ENV }}

      - uses: amondnet/vercel-action@v19
        with:
          working-directory: web
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.PR_COMMENTS_GITHUB_TOKEN }}
          scope: ${{ secrets.WEB_ORG_ID }}
          vercel-org-id: ${{ secrets.WEB_ORG_ID }}
          vercel-project-id: ${{ secrets.WEB_PROJECT_ID }}
          vercel-args: "--prod"

      - name: update deployment status
        uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ env.DEPLOYMENT_DOMAIN }}
